# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "crates/database/src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]
filter.except_tables = [
	"device_connections_\\d+w\\d+",
	"statuses_\\d+w\\d+",
]

[migrations_directory]
dir = "migrations"
